# -*- coding: utf-8 -*-
"""MaverickPredictorX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-znCliRZpFwtdASqjFSIrSQWWGV-63Fe

The Naive Bayes Classification model
"""

#MaverickPredictor X source code
#Made by Aryan Patil for Merge Intern Hackathon 2021

#importing modules
import numpy as np
import pandas as pd

#reading the dataset
dataset = pd.read_csv('values.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#splitting the dataset into testing and training set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#training the model
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

#user input for testing if he/she will fit the company's culture
welcome = print("""Welcome to MaverickPredictor X, a highly accurate Naive Bayes classification model
which predicts if an employee is suitable for the company culture.""")

q1 = int(input("What is your age?: "))
q2 = input("Do you prefer a relaxed enviorment or an on-demand one? (relaxed/on-demand): ")
if q2 == "relaxed":
  q2 = 1
else:
  q2 = 0

q3 = input("Is a work-life balance important to you? (yes/no): ")
if q3 == "yes":
  q3 = 1
else:
  q3 = 0

q4 = input("Do you like feedback about your work? (yes/no): ")
if q4 == "yes":
  q4 = 1
else:
  q4 = 0

q5 = input("Do you handle stress properly? (yes/no): ")
if q5 == "yes":
  q5 = 1
else:
  q5 = 0

q6 = input("Do you prefer to work in a team or alone? (team/alone): ")
if q6 == "team":
  q6 = 0
else:
  q6 = 1

q7 = input("Have you done anything for charity? (yes/no): ")
if q7 == "yes":
  q7 = 1
else:
  q7 = 0

print("Analysing answers...")
result = classifier.predict(sc.transform([[q1,q2,q3,q4,q5,q6,q7]]))
print("   ")
if result == [1]:
  print("Congratulations! your profile is a perfect fit for our company!")
else:
  print("Sorry, your profile is not a fit for our company. Please try in the future.")
  print("Here are some possible reasons why your profile wasn't a fit:")
  print("")
  if q3 == 0:
    print("You seem to not be able to balance work and life very well.")
  if q4 == 0:
    print("You don't like feedback")
  if q5 == 0:
    print("You cannot handle stress properly")
  else:
    print("Good luck next time!")
print("Thank you for using MaverickPredictor X!")